# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170323_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
