# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20170327_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourses',
            options={'verbose_name': 'MyCourses'},
        ),
    ]
