# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lecture_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order', 'title']},
        ),
    ]
