# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:07
from __future__ import unicode_literals

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20170326_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='order',
            field=apps.utils.fields.PositionField(default=-1),
        ),
    ]
