# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20170327_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='owned_courses', to='courses.Course'),
        ),
    ]
