# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    replaces = [('videos', '0001_initial'), ('videos', '0002_video_title'), ('videos', '0003_auto_20170315_2322'), ('videos', '0004_video_slug'), ('videos', '0005_auto_20170319_2254'), ('videos', '0006_auto_20170319_2258')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed_code', models.TextField()),
                ('title', models.CharField(default='test', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2017, 3, 15, 22, 22, 27, 561730, tzinfo=utc))),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('free', models.BooleanField(default=True)),
                ('member_required', models.BooleanField(default=False)),
            ],
        ),
    ]
