# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2017, 3, 15, 22, 22, 27, 561730, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
